<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'opensanscondensed-light' => array(
    'normal' => $rootDir . '/lib/fonts/OpenSansCondensed-Light',
    'bold' => $rootDir . '/lib/fonts/OpenSansCondensed-Light',
    'italic' => $rootDir . '/lib/fonts/OpenSansCondensed-Light',
    'bold_italic' => $rootDir . '/lib/fonts/OpenSansCondensed-Light',
  ),
  'opensanscondensed-bold' => array(
    'normal' => $rootDir . '/lib/fonts/OpenSans_Bold',
    'bold' => $rootDir . '/lib/fonts/OpenSans_Bold',
    'italic' => $rootDir . '/lib/fonts/OpenSans_Italic',
    'bold_italic' => $rootDir . '/lib/fonts/OpenSans_Bold_Italic',
  ),
  'opensans' => array(
    'normal' => $fontDir . '/opensans-normal_bdef217692a0f97ecbdab9b6871737a7',
    'bold' => $fontDir . '/OpenSans_Bold',
    'italic' => $fontDir . '/OpenSans_Italic',
    'bold_italic' => $fontDir . '/OpenSans_Bold_Italic',
  ),
  'opensans-light' => array(
    'normal' => $fontDir . '/OpenSans_Light',
    'bold' => $fontDir . '/OpenSans_Light',
    'italic' => $fontDir . '/OpenSans_Light_Italic',
    'bold_italic' => $fontDir . '/OpenSans_Light',
  ),
  'lato' => array(
    'normal' => $fontDir . '/Lato',
    'bold' => $fontDir . '/Lato_Bold',
    'italic' => $fontDir . '/Lato',
    'bold_italic' => $fontDir . '/Lato_Bold_Italic',
  ),
  'lato-bold' => array(
    'normal' => $fontDir . '/Lato_Bold',
    'bold' => $fontDir . '/Lato_Bold',
    'italic' => $fontDir . '/Lato_Bold',
    'bold_italic' => $fontDir . '/Lato_Bold',
  ),
  'lato-bold-italic' => array(
    'normal' => $fontDir . '/Lato_Bold_Italic',
    'bold' => $fontDir . '/Lato_Bold_Italic',
    'italic' => $fontDir . '/Lato_Bold_Italic',
    'bold_italic' => $fontDir . '/Lato_Bold_Italic',
  ),
) ?>